version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: timetracker-app-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/timetracker
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - timetracker-network

  db:
    image: postgres:16-alpine
    container_name: timetracker-db-dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timetracker
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - timetracker-network

networks:
  timetracker-network:
    driver: bridge

volumes:
  postgres_data_dev: