  version: '3.8'

<<<<<<< HEAD
  services:
    app:
      build:
        context: .
        dockerfile: Dockerfile.dev
      container_name: timetracker-app-dev
      restart: unless-stopped
      ports:
        - "5000:5000"
      environment:
        - NODE_ENV=development
        - DATABASE_URL=postgres://root:root@db:5432/timetracker
      volumes:
        - .:/app
        - /app/node_modules
      depends_on:
        - db
=======
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: timetracker-app-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - ./.env:/app/.env
    networks:
      - timetracker-network
>>>>>>> 1e388cd (Translate documentation and improve Docker setup for better clarity)

    db:
      image: bitnami/postgresql:latest
      container_name: timetracker-db-dev
      restart: unless-stopped
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=timetracker
      volumes:
        - postgres_data_dev:/var/lib/postgresql/data


  volumes:
    postgres_data_dev: