version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: timetracker-app-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://${DEV_DB_USER:-root}:${DEV_DB_PASSWORD:-root}@db:5432/${DEV_DB_NAME:-timetracker}
      - TZ=America/Sao_Paulo
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - timetracker-dev-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: bitnami/postgresql:latest
    container_name: timetracker-db-dev
    restart: unless-stopped
    ports:
      - "${DEV_DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DEV_DB_USER:-root}
      - POSTGRES_PASSWORD=${DEV_DB_PASSWORD:-root}
      - POSTGRES_DB=${DEV_DB_NAME:-timetracker}
      - TZ=America/Sao_Paulo
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DEV_DB_USER:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - timetracker-dev-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pgadmin-dev:
    container_name: timetracker-pgadmin-dev
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DEV_PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${DEV_PGADMIN_PASSWORD:-root}
      TZ: America/Sao_Paulo
    ports:
      - "${DEV_PGADMIN_PORT:-5051}:80"
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - timetracker-dev-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data_dev:
    name: timetracker_postgres_data_dev
  pgadmin_data_dev:
    name: timetracker_pgadmin_data_dev

networks:
  timetracker-dev-network:
    name: timetracker-dev-network
    driver: bridge