name: Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Run weekly

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        
    - name: Install npm audit
      run: npm install -g npm-audit-resolver
      
    - name: Run npm audit
      run: npm audit --production
      continue-on-error: true
      
    # You can add additional security scanning tools here
    # For example, CodeQL, SonarQube, etc.
